Add item requests
TatianaAV/java-shareit pull request #3
Opened 2023-02-28 23:50 UTC by TatianaAV

2023-03-01 22:06 UTC, NikolaiDem requested changes
Для методов с кастомными запросами BookingRepository и ItemRepository тоже нужны тесты. И для всех модулей лучше добавить интеграционные тесты (в таких тестах поднимается полноценный контекст с бинами, использовать @SpringBootTest)
 с некоторыми кейсами, например, тестирование сценария на создание бронирования, запроса.

2023-03-01 22:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dto/GetBookings.java
> +public class GetBookings {
Классы лучше называть существительными.

2023-03-01 22:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                if ((booking.getStatus().equals(StatusBooking.WAITING)
Одиночный if выглядит проще:
if (!approved &&
         (booking.getStatus().equals(StatusBooking.WAITING) || booking.getStatus().equals(StatusBooking.APPROVED))) {}

2023-03-01 22:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/exeption/ErrorHandler.java
>      @ExceptionHandler
Закомментированный код лучше удалить. Для восстановления истории гит может помочь)

2023-03-01 22:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query("select i from Item i where i.request.requestId = :requestId")
А явный запрос можно не прописывать, ведь query method написан в соответствии с правилами.

2023-03-01 22:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Item newItem = new Item();
Маппинг item в newItem выглядит как метод маппера. В него можно передать item и request.

2023-03-01 22:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +public class ItemRequestController {
Логирование запросов тоже лучше добавить.

2023-03-01 22:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/dto/AddItemRequest.java
> +public class AddItemRequest {
Классы лучше называть существительными.

2023-03-01 22:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/dto/GetItemRequest.java
> +public class GetItemRequest {
Классы лучше называть существительными.

2023-03-01 22:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +public class ItemRequest {
Все поля лучше сделать private.

2023-03-01 22:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                .peek(request -> request.setItems(itemMapper.mapItemDto(items.getOrDefault(request.getId(),
peek рекомендуется использовать только для отладки. Например, сонар говорит так:
https://rules.sonarsource.com/java/RSPEC-3864
Можно заменить на map или forEach

2023-03-02 14:48 UTC, TatianaAV commented on src/main/java/ru/practicum/shareit/booking/dto/GetBookings.java
> +public class GetBookings {
Честно взято из примера курса https://github.com/praktikum-java/module4_spring_without_boot/tree/business_logic

2023-03-03 00:45 UTC, TatianaAV commented
Добрый день, рада, что вернулись! В этой когорте ни у кого нет спрингбут тестов. Пришлось спрашивать в 6.

2023-03-03 22:47 UTC, NikolaiDem approved these changes

2023-03-04 00:04 UTC, merged